# copy node base image 
FROM node:22-alpine

# specify working path
WORKDIR /cramble

# copy package*.json
COPY package*.json ./

# install app dependencies
RUN npm install

# copy remaining files
COPY . .

# expose the port
EXPOSE 3000

# build source code to generate /dist folder
RUN npm run build

# run the server
CMD [ "node", "dist/index.js" ]
